{{- if and .Values.ssh.hostKey.privateKey (not .Values.ssh.hostKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "containerssh.fullname" . }}-hostkey
  labels:
    {{- include "containerssh.labels" . | nindent 4 }}
type: Opaque
data:
  host.key: {{ .Values.ssh.hostKey.privateKey | b64enc | quote }}
{{- end }}
