apiVersion: v2
name: containerssh
description: An SSH server for on-demand or persistent Kubernetes pods with audit logging. This chart deploys
  ContainerSSH with the Kubernetes backend.
type: application

# This is the chart version. Bump this when you change the chart itself.
version: 0.1.9

# This is the ContainerSSH version the chart is tested/validated against.
appVersion: "0.6"

home: https://containerssh.io
icon: https://containerssh.github.io/images/logo-for-embedding.svg
sources:
  - https://github.com/ContainerSSH/ContainerSSH
maintainers:
  - name: dev.box
  - name: ContainerSSH Contributors
    url: https://containerssh.io
keywords:
  - ssh
  - containers
  - kubernetes
  - ephemeral
  - persistent
annotations:
  category: Infrastructure
